services:
  monitor:
    build: .
    container_name: snmp-monitor
    ports:
      - "${PORT:-8501}:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
    command: >
      streamlit run monitor_snmp.py
        --server.port=8501
        --server.enableCORS=false
